name: Manual test

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT: 
        type: choice
        description: On which environment should I run checks?
        options:
        - DEV
        - DEMO
        - QA
      GROUPS:
        description: 'Choose test groups to run from [admin, employee, retro]. Single group example: group1. Multiple groups separated with comma: group1,group2. By default all groups are selected.'
        default: ''
      EXCLUDE_GROUPS:
        description: 'Choose test groups to exclude from run. Single group example: group1. Multiple groups separated with comma: group1,group2.'
        default: 'retro,templates'
      WHERE_TO_RUN:
        description: Choose where to run?
        type: choice
        options:
        - web
        - mobile
        
env:
  WHERE_TO_RUN: ${{ inputs.WHERE_TO_RUN }}
  AWS_SECRET_DEV: "secret"
  AWS_SECRET_QA: "now way"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 17
          maven-version: 3.8.6
          
      - name: test
        run: mvn -v

