name: Manual test

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT: 
        type: choice
        description: On which environment should I run checks?
        options:
        - DEV
        - DEMO
        - QA
      GROUPS:
        description: 'Choose test groups to run from [admin, employee, retro]. Single group example: group1. Multiple groups separated with comma: group1,group2. By default all groups are selected.'
        default: ''
      EXCLUDE_GROUPS:
        description: 'Choose test groups to exclude from run. Single group example: group1. Multiple groups separated with comma: group1,group2.'
        default: 'retro,templates'
      WHERE_TO_RUN:
        description: Choose where to run?
        type: choice
        options:
        - web
        - mobile
        
env:
  WHERE_TO_RUN: web
  AWS_SECRET_DEV: "secret"
  AWS_SECRET_QA: "now way"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: fixing permissions for allure
        run: chmod -R 777 $GITHUB_WORKSPACE/target/allure-results

      - name: Install allure
        run: |
          curl -o allure-2.17.3.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.3/allure-commandline-2.17.3.tgz
          sudo tar -zxf allure-2.17.3.tgz -C /opt/
          sudo ln -s /opt/allure-2.17.3/bin/allure /usr/bin/allure

      - name: Run report
        run: allure generate $GITHUB_WORKSPACE/target/allure-results

      - name: List
        run: |
          ls -la $GITHUB_WORKSPACE/target/allure-results
          pwd

