# This is a basic workflow to help you get started with Actions

name: CI/CD main

env:
  SERVICE_NAME: hsc-fe
  AWS_ECR_ACCOUNT_URL: 481193184231.dkr.ecr.us-west-2.amazonaws.com
  MAIN_BRANCH_NAME: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
 push:
   branches:
     - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: script
        run: |
          chmod 700 hello.sh
          ./hello.sh
      
      - name: Install soft
        run: |
          curl -o allure-2.17.3.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.3/allure-commandline-2.17.3.tgz
          sudo tar -zxf allure-2.13.8.tgz -C /opt/
          sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure
          allure --version
