name: Pull request check

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
        
  pull_request:
    types: [opened, reopened]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_BASE: ${{github.event.pull_request.base.ref}}
  CURRENT_BRANCH: ${{github.event.pull_request.head.ref}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: input
        run: echo "${{ inputs.environment }}"

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: SonarQube scan
        uses: ./.github/actions/test
        with:
          PR_ID: ${{ env.GITHUB_PR_NUMBER }}
          BASE_BRANCH: ${{ env.GITHUB_BASE }}
          CURRENT_BRANCH: ${{ env.CURRENT_BRANCH }}
          PLACE: "pullRequest=${{ env.GITHUB_PR_NUMBER }}"
          ENV: dev
          AWS_TESTDATA_SECRET_NAME: secret
          WHERE_TO_RUN: ${{ inputs.WERE_TO_RUN }}
